roleコマンドを追加
brokenManager/OreOreBot pull request #103
Opened 2020-04-08 15:31 UTC by Colk-tech

Reviewを待たなければいけなくなりました(半ギレ)

2020-04-08 15:32 UTC, Colk-tech commented
`Review required`(絶望)

2020-04-08 15:34 UTC, Colk-tech commented
At least 1 approving review is required to merge this pull request.
(絶望)

2020-04-08 15:54 UTC, isso0424 reviewed
***†REQUEST CHANGES†***

2020-04-08 15:54 UTC, isso0424 commented on lib/role.py
> +            await channel.send("そんなユーザーIDのメンバーはいないよ...?")
***†GUARD†***

2020-04-08 15:54 UTC, isso0424 commented on lib/role.py
> +    async def role(self, commands, channel, member_name):
commandsの中身とそれに対応する挙動書こうね

2020-04-08 15:54 UTC, isso0424 commented on lib/role.py
> +        await channel.send("<@&{}>を作成して<@!{}>に付与しました！".format(str(created_role.id),str(target.id)))
str()いらんが

2020-04-08 15:54 UTC, isso0424 commented on lib/role.py
> +        if channel.guild.get_member(int(commands[1])) == None:
1回commands[1]をuser_idとかに取り出せ

2020-04-08 15:54 UTC, isso0424 commented on lib/role.py
> +            name = commands[2]
上の方で中身取り出せ

2020-04-08 15:54 UTC, isso0424 commented on lib/role.py
> +                color = discord.Colour.from_rgb(int(commands[3][1:3],16),int(commands[3][3:5],16),int(commands[3][5:7],16))
1個1個RGBに取り出そうね

2020-04-08 15:54 UTC, isso0424 commented on lib/role.py
> +            except:
キャッチするエラーを明示しろ

2020-04-08 15:55 UTC, isso0424 requested changes
変えろ

2020-04-08 15:56 UTC, Colk-tech commented on lib/role.py
> +            await channel.send("そんなユーザーIDのメンバーはいないよ...?")
e53cec4deeb66c45a0a6d69370edba6c0aeae30e で解決

2020-04-08 15:58 UTC, Colk-tech commented on lib/role.py
> +        if channel.guild.get_member(int(commands[1])) == None:
de0ca65430c132a4937b4f853b40165997516150 解決済み

2020-04-08 16:00 UTC, isso0424 reviewed
,の後にspace入れようね

2020-04-08 16:00 UTC, isso0424 commented on lib/role.py
> +                color = discord.Colour.from_rgb(int(commands[3][1:3],16),int(commands[3][3:5],16),int(commands[3][5:7],16))
,の後にspace入れろ

2020-04-08 16:00 UTC, isso0424 commented on lib/role.py
> +        await channel.send("<@&{}>を作成して<@!{}>に付与しました！".format(created_role.id,target.id))
,の後にspace入れようね

2020-04-08 16:10 UTC, Colk-tech commented on lib/role.py
> +    async def role(self, commands, channel, member_name):
これ全部の機能に対して書かなきゃいけねーじゃねーか

2020-04-08 16:12 UTC, Colk-tech commented on lib/role.py
> +    async def role(self, commands, channel, member_name):
というわけでこれは別issue行きです

2020-04-08 16:14 UTC, isso0424 commented on lib/role.py
> +    async def role(self, commands, channel, member_name):
いやここのやつは少なくとも書けや

2020-04-08 16:15 UTC, Colk-tech commented on lib/role.py
> +    async def role(self, commands, channel, member_name):
かなしいね 書きます

2020-04-08 20:18 UTC, Colk-tech commented
ちなみにpylintくんによる評価では
`Your code has been rated at 5.00/10`だそうです
正直-行くと思ってたゾ

2020-04-08 20:48 UTC, Colk-tech commented
たぶんもうええやろ

2020-04-08 20:58 UTC, isso0424 requested changes
なんでこれで通ると思ったんですか
***†REQUEST CHANGES†***

2020-04-08 20:58 UTC, isso0424 commented on lib/role.py
> +            role_name = commands[2]
こいつらifの前で展開できますよね

2020-04-08 20:58 UTC, isso0424 commented on lib/role.py
> +        created_role = await channel.guild.create_role(name=role_name, color=color,
commandsが5以上のときの処理が無い

2020-04-08 20:58 UTC, isso0424 commented on lib/role.py
> +            role_name = commands[2]
こいつら(ry

2020-04-08 20:58 UTC, isso0424 commented on lib/role.py
> +            target_user = channel.guild.get_member(int(user_id))
これもif文の前で書けますよね

2020-04-08 20:58 UTC, isso0424 commented on lib/role.py
> +            target_user = channel.guild.get_member(int(user_id))
これも(ry

2020-04-08 20:58 UTC, isso0424 commented on message_command.py
> +            await role.role(commands, self.channel, self.member_name)
classである意味無くね

2020-04-08 20:58 UTC, isso0424 commented on lib/role.py
> +特にデータを保持することもないと思うので関数になります
じゃあそうしてください

2020-04-08 20:58 UTC, isso0424 commented
ぜんぜんよくないです

2020-04-08 21:27 UTC, Colk-tech commented
うぅ...

2020-04-08 21:27 UTC, isso0424 commented
つよく改善して

2020-04-08 21:27 UTC, Colk-tech commented
***†REREQUEST CHANGES†***ですね

2020-04-08 21:27 UTC, Colk-tech commented
すみませんでした

2020-04-08 21:33 UTC, Colk-tech commented on lib/role.py
> +        created_role = await channel.guild.create_role(name=role_name, color=color,
あー盲点

2020-04-08 21:39 UTC, Colk-tech commented
おかげさまでだいぶ読みやすくなりました👐

2020-04-08 21:47 UTC, isso0424 requested changes
なんでまだ見つかるんだ(困惑)

2020-04-08 21:47 UTC, isso0424 commented on lib/role.py
> +    commands[3] = (任意)↑のカラーコードです"#ffffff"で指定します
docstringにはtypeも追記しましょう
あとchanelとmember_nameについても書きましょう

2020-04-08 21:47 UTC, isso0424 commented on lib/role.py
> +    if len(commands) <= 5:
不等号逆です

2020-04-08 21:47 UTC, isso0424 commented on lib/role.py
> +            await channel.send("カラーコードの形式が間違っているよ")
ガード忘れ

2020-04-08 21:58 UTC, Colk-tech commented
ミスがガバ過ぎて草
テスしろ

2020-04-09 04:06 UTC, isso0424 approved these changes
***†APPROVE†***

2020-04-09 08:54 UTC, Colk-tech commented
道のり ながい

2020-04-09 08:55 UTC, merged

2020-04-09 09:04 UTC, isso0424 commented
こーど　がばい