kaereの切断処理を追加、なんで今までなかったんだろうね
brokenManager/OreOreBot pull request #108
Opened 2020-04-11 16:46 UTC by isso0424

たのしいね

2020-04-11 16:47 UTC, potyama commented
***†APPROVE†***

2020-04-11 16:47 UTC, shun-shobon commented
***承認しません***

2020-04-11 16:47 UTC, mirror-kt requested changes
Never Approve

2020-04-11 16:47 UTC, ko50 commented
request changes

2020-04-11 16:47 UTC, shun-shobon reviewed
***承認しないんだお***

2020-04-11 16:48 UTC, potyama requested changes
なんか納得行かないから　***†Request changes†***

2020-04-11 16:48 UTC, ko50 requested changes
†Approve†

2020-04-11 16:48 UTC, 2RiniaR requested changes
approveなんて...してあげないこともないんだからねっ///

2020-04-11 16:48 UTC, kawaemon requested changes
***†APPROVE†***

2020-04-11 16:48 UTC, UniokaWorld requested changes
日本人なのでみんなに合わせる

2020-04-11 16:49 UTC, shun-shobon requested changes
なんかいっそうがムカつくので ***非承認***

2020-04-11 16:49 UTC, UniokaWorld commented
UniokaWorld requested a review from potyama
すまん

2020-04-11 16:49 UTC, mirror-kt approved these changes
しょうがないなぁ

2020-04-11 16:50 UTC, potyama requested changes
してあげるよ

2020-04-11 16:50 UTC, MikuroXina approved these changes
修正要件は 0 件です
以下の通りに修正してください

2020-04-11 16:51 UTC, shun-shobon reviewed
***†DISAPPROVE†***

2020-04-11 16:51 UTC, potyama approved these changes
現代おごりで

2020-04-11 16:51 UTC, UniokaWorld approved these changes
**つよくいきよう**
　　　　　　　　　　　　◢◤▆▇▆◣
　　　　　　　　　　　◢▉■◢▊██◣▃▂
　　　　　　　　　 ◢▐▅██ ▋██◤◢▅▇◣
　　　　　　 　 ◢█▆◥███◤▇█◤██◢▇▀◣
　　　　　　 ◢██▼▀　　　　　　▀▓█◤〓█◣
　　　　　　██▌░: 　　　　　　　　 ◥█◤◢▇█▍
　　　　　▐██:░::　　　　　.: 　 　 　▓█▀▅▇▍
　　 　 　 ██▍◢〓▅▂　　▂▃▬◣　 ◥█◣◥▇█
　　　　　　▀▌ ◢■◣ ▓ 　.:◢▆▅◣　　 ▼▀▌▼
　　　　　　　▍ 　 　 :░　　　　　　　　◢█ ▐▀
　 　 　 　 　 ▎ 　 　:░　　　　　　　.:　◤ ◢◤
　　　　　 　　▍::　　 ▀◣◢◣　　　　.:░:▂◤
　　 　 　 　　▐░:: ▄▅▃◢◣▂　 　:░◤▂
　　　　　　 　▲░░::　　　　　.: █◥▋◣
　　　　　　 ◢░▓◣░::　　　　　◢◤　▀▓◤　◥◣▂
　　　 　▅░░:▓▓◣▓〓◢◤　　▓◤　　　◥█▃
　 　 ◢█░░:: ▓▓▓◣▀▓░::　 ▓▓◤.:　　　 ██▓
　◢▇▓█:░░:: ▓▓▓◣ :░:: ▓▓▓▋.::　　　 ███▓▌◥◣
◢░▓██ ░░:: ▓▓▓▓◤ ◢▓▓▓▓▌░:: .:　 ██▓█▓▍ 　◥◣
.:░▓██▌░░:: ▓▓▀ ▓▓▓▓▓▍░::░::: █▓█▓▓█　　　▲
▓█▓█▌:░░::▼ ▓▓▓▓▓▓▍:░░░::██▓▓▓■ ▓

2020-04-11 16:51 UTC, shun-shobon approved these changes
***†DISAPPROVE†***

2020-04-11 16:51 UTC, ko50 approved these changes
樋口一葉くれるんだったらいいよ

2020-04-11 16:52 UTC, 2RiniaR approved these changes
I love you

2020-04-11 16:52 UTC, shun-shobon requested changes
いっそうを ***†認めたくない†***

2020-04-11 16:53 UTC, MikuroXina approved these changes
バグ修正ヨシ！

2020-04-11 16:53 UTC, shun-shobon approved these changes
(よくわからんけどとにかく) ***†ヨシ！†***

2020-04-11 16:55 UTC, MikuroXina approved these changes
大丈夫っぽい

2020-04-11 16:55 UTC, mirror-kt requested changes
コード読み直すのでrequest changes

2020-04-11 16:56 UTC, shun-shobon approved these changes
***†大草原†***
![スクリーンショット 2020-04-12 1 56 15](https://user-images.githubusercontent.com/37236438/79049865-fb1e6800-7c60-11ea-8ee7-cc63dff73385.png)

2020-04-11 16:58 UTC, kawaemon approved these changes

2020-04-11 16:58 UTC, potyama requested changes
tyottomatte

2020-04-11 16:58 UTC, shun-shobon approved these changes
***†これが現実†***
![shun-shobon (1)](https://user-images.githubusercontent.com/37236438/79049881-2a34d980-7c61-11ea-8e9c-cccaf5a1caea.png)

2020-04-11 16:59 UTC, mirror-kt approved these changes
ヨシ!

2020-04-11 17:04 UTC, potyama approved these changes

2020-04-11 17:04 UTC, merged

2020-04-11 21:36 UTC, Colk-tech commented
何だこの地獄みたいなPRは...

2020-04-11 21:37 UTC, Colk-tech commented
> approveなんて...してあげないこともないんだからねっ///

通報しました

2020-04-11 23:13 UTC, loxygenK commented
えっ何このPR

2020-04-12 09:13 UTC, isso0424 commented
***†MIDNIGHT TENSION†*** の賜物