国勢調査を実装
brokenManager/OreOreBot pull request #111
Opened 2020-04-13 00:09 UTC by Colk-tech

Approve 1つ以上で Merge
`!number`, `!zinnkou`, `!zinkou`, `!population`を検知すると変更のあった行を次の形式で送信します:
```
***†只今の限界開発鯖の人口†***
・通常ユーザー: {} 人
・Botユーザー: {} 人
・Bot率: {}%```"
```

2020-04-13 00:14 UTC, Colk-tech commented
参照 : #109

2020-04-13 00:18 UTC, Colk-tech commented
ブランチの切り所間違えて別実装と一本になってるので内容については #109 を必ず参照してください

2020-04-13 01:28 UTC, Colk-tech commented
#111 をReviewしろ

2020-04-13 04:25 UTC, loxygenK reviewed
いろいろコメントしてしまったのでApproveしにくいので ***†Comment†*** だけにしておきます

2020-04-13 04:25 UTC, loxygenK commented on lib/kokusei_chousa.py
> +    bot_ratio = float(bot_number) / (float(bot_number) + float(user_number))
```suggestion
    bot_ratio = bot_number) / (bot_number + user_number)
```
floatいらないはずだで
テストしてないので動かなかったらすまんこ

2020-04-13 04:25 UTC, loxygenK commented on main.py
> +        with codecs.open(os.path.dirname(__file__) + "/messages.json", 'r', 'utf-8') as json_file:
```suggestion
        with codecs.open(os.getcwd() + "/messages.json", 'r', 'utf-8') as json_file:
```
how about dis? ただの提案なので無視しても大丈夫やで♥

2020-04-13 04:25 UTC, loxygenK commented on message_command.py
> +        with codecs.open(os.path.dirname(__file__) + "/messages.json", 'r', 'utf-8') as json_file:
```suggestion
        with codecs.open(os.getcwd() + "/messages.json", 'r', 'utf-8') as json_file:
```
今気づいたんですけど同じコード2つあるんだなこれ
初めて知った

2020-04-13 10:32 UTC, isso0424 reviewed
Request Changesほどじゃないが気になったので ***Comment***

2020-04-13 10:32 UTC, isso0424 commented on lib/editmiteta.py
> +    if composed_text == "":
trimして空白とか改行とか無視して判定しないんか?

2020-04-13 10:32 UTC, isso0424 commented on lib/kokusei_chousa.py
> +            user_number += 1
```suggestion
    for member in channel.guild.members:
        if member.bot:
            bot_number += 1
            continue
        user_number += 1
```

これでも良い気はする

2020-04-13 10:32 UTC, isso0424 commented on lib/kokusei_chousa.py
> +            user_number += 1
てか人数取るだけなら
```python
all_members_number = len([m for m in channel.guild.members])
bot_number = len([m for m in channel.guild.members if m.bot])
user_number = all_members_number - bot_number
```
でも取れるな

良いかどうかは別として

2020-04-13 10:32 UTC, isso0424 commented on lib/editmiteta.py
> +async def mitetazo_edit(before, after):
typehint書きません?

2020-04-13 10:32 UTC, isso0424 commented on lib/editmiteta.py
> +    after_text = after.content
この時点でsplitした場合って不都合ある?

2020-04-13 11:08 UTC, Colk-tech commented on lib/editmiteta.py
> +async def mitetazo_edit(before, after):
わすれてた
かくあ

2020-04-13 11:30 UTC, Colk-tech commented on lib/editmiteta.py
> +    after_text = after.content
(特に)無いです。
かえますね

2020-04-13 11:32 UTC, Colk-tech commented on lib/kokusei_chousa.py
> +            user_number += 1
その手もあるのか
リスト内包括のほうがわかりやすいかなぁ...

2020-04-13 11:34 UTC, Colk-tech commented on lib/kokusei_chousa.py
> +    bot_ratio = float(bot_number) / (float(bot_number) + float(user_number))
できますねぇ！

2020-04-13 11:34 UTC, Colk-tech commented on lib/editmiteta.py
> +    if composed_text == "":
あーやります

2020-04-13 18:52 UTC, isso0424 requested changes
すまんこれは駄目です
***REQUEST CHANGES***

2020-04-13 18:52 UTC, isso0424 commented on lib/editmiteta.py
> +    if composed_text == "":
やりましたか...?

2020-04-13 18:52 UTC, isso0424 commented on lib/editmiteta.py
> +    Returns
listに書き直そうね

2020-04-13 18:52 UTC, isso0424 commented on lib/kokusei_chousa.py
> +    bot_ratio = bot_number) / (bot_number + user_number)
bot_number)ってこれエラー吐くやろ

2020-04-13 18:52 UTC, isso0424 commented on lib/kokusei_chousa.py
> +    await channel.send(NUMBER_TEXT.format(user_number, bot_number, round(bot_ratio, 3) * 100))
rount(bot_ratio, 3) * 100は28行目にまとめてしまったほうが良い気がする

2020-04-13 18:52 UTC, isso0424 commented
あと解決せずにresolveするのをやめなさい

2020-04-13 18:53 UTC, Colk-tech commented
眠くなりながら書いてたから全然気づかなかったです()
仕事帰りだから仕方ないね

2020-04-13 23:58 UTC, Colk-tech commented on lib/editmiteta.py
> +    after_text = after.content
(無いと思うが)もし関数を再利用することを考えてそのままにしておきます

2020-04-14 00:42 UTC, loxygenK requested changes
バグになりそうなものを見つけたので ***†REQUEST CHANGES†***

2020-04-14 00:42 UTC, loxygenK commented on main.py
> +        with codecs.open(os.getcwd() + "./messages.json", 'r', 'utf-8') as json_file:
```suggestion
        with codecs.open(os.getcwd() + "/messages.json", 'r', 'utf-8') as json_file:
```
ディレクトリ名が変なことになってァ！するゾ

2020-04-14 00:42 UTC, loxygenK commented on message_command.py
> +        with codecs.open(os.getcwd() + "./messages.json", 'r', 'utf-8') as json_file:
```suggestion
        with codecs.open(os.getcwd() + "/messages.json", 'r', 'utf-8') as json_file:
```

2020-04-14 00:42 UTC, loxygenK commented on lib/editmiteta.py
> +async def mitetazo_edit(before: discord.Message, after: discord.Message):
```suggestion
async def mitetazo_edit(before: String, after: String):
```
ではいけませんか…？

2020-04-14 00:46 UTC, Colk-tech commented
無言でReReReReRequestすんな

2020-04-14 00:50 UTC, loxygenK approved these changes
***†Approve†***
ちなみに今起きてから5分後ぐらいです
おはようございます、いい天気ですね

2020-04-14 00:51 UTC, Colk-tech commented
やば
yようやくApproveだ...

2020-04-14 00:53 UTC, loxygenK commented
たのしいね

2020-04-14 00:53 UTC, loxygenK commented
いっそうくんがApproveしないとmergeできないのか大変だなこれ

2020-04-14 05:30 UTC, isso0424 commented on lib/editmiteta.py
> +async def mitetazo_edit(before: discord.Message, after: discord.Message):
これ駄目でしょチャンネル取ってる

2020-04-14 05:32 UTC, Colk-tech commented on lib/editmiteta.py
> +async def mitetazo_edit(before: discord.Message, after: discord.Message):
かなしいね...

2020-04-14 05:33 UTC, isso0424 commented on lib/editmiteta.py
> +    diff_text_list = [i for i in diff_list if i.startswith("+") or i.startswith("-")]
私気になったんですがこれって+または-が先頭につく関係ない文章はどう判定されるんですか

2020-04-14 05:34 UTC, isso0424 commented
これバグらないの?
見た感じバグりそうだと思ったんだが

2020-04-14 05:35 UTC, Colk-tech commented
変更されてないとバグるかも知れん
でもdiffに通した時点で+とか-でしか返ってこないので自前で対応しないといけない

2020-04-14 05:35 UTC, Colk-tech commented
ためしてみるか

2020-04-14 05:38 UTC, Colk-tech commented
@isso0424 
バグりませんでした対戦ありがとうございました
ほんとうにうれしいです

2020-04-14 05:39 UTC, Colk-tech commented on lib/editmiteta.py
> +    diff_text_list = [i for i in diff_list if i.startswith("+") or i.startswith("-")]
バグりませんでした対戦ありがとうございました
ほんとうにうれしいです

2020-04-14 05:44 UTC, isso0424 approved these changes
***†Approve†***

2020-04-14 05:44 UTC, isso0424 commented
てか想定される不具合は先にテストしなさいよ...

2020-04-14 05:45 UTC, Colk-tech commented
根気よくレビューしてくれるお二人大好きだよ❤
@isso0424 @loxygenK

2020-04-14 05:45 UTC, merged