Tukareta
brokenManager/OreOreBot pull request #116
Opened 2020-04-18 04:34 UTC by Colk-tech

† ***閲覧注意*** †

とてつもないウンコードです

2020-04-18 04:37 UTC, Colk-tech commented
2人以上のApproveでmergeします

2020-04-18 05:03 UTC, loxygenK commented
よーし！おじさんがんばってReviewしちゃうぞ！

2020-04-18 05:29 UTC, loxygenK requested changes
(気になる点が)いっぱいいっぱい…入っちゃ…！(***REQUEST CHANGES***)
それではウンコードライターによるお気持ち表明を執り行います。

2020-04-18 05:29 UTC, loxygenK commented on lib/voice_manager.py
> +        if after.channel == before.channel or member.id in [684295118643265548]:
`[684295118643265548]`を配゛列゛変゛数゛に゛入゛れ゛て゛く゛れ゛な゛ん゛の゛や゛つ゛か゛パ゛ッ゛ト゛見゛わ゛か゛ら゛ん゛

2020-04-18 05:29 UTC, loxygenK commented on lib/voice_manager.py
> +        self.is_join = None
`self.is_join`とか`self.member` を`self.embed_generator()`と`self.role_manager()`関数の引数にして渡したいお気持ちがつよい
これについて考えがあるのでこのPRがmergeされたらリファクタしてみてもいいですか?

2020-04-18 05:29 UTC, loxygenK commented on lib/voice_manager.py
> +                                  description="あいつは良い奴だったよ...", color=0x1e63e9)
```suggestion
        if self.is_join:
            embed_title = "{}が{}に入りました"
            embed_message = "何かが始まる予感がする。"
        else: #<--- !!!!!!!!!!!!!!!!!!!!!!!!!
            embed_title = "{}が{}にから抜けました"
            embed_message = "あいつは良い奴だったよ…"
        embed_out = discord.Embed(title=embed_title.format(self.member.display_name, str(self.before.channel)), description=embed_message, color=0x1e63e9)
```
ここ変数使ってどうにか出来ないかなって思ってコメントつけようとしたんですけど`else警察`の存在を思い出したのでなんでもないです
三項演算子でかいくぐろうかと思ったけどウンコードだしPythonの三項演算子カスだし警察いそうなのでいいです

2020-04-18 05:29 UTC, loxygenK commented on main.py
> +        """
ｗｗｗｗｗｗｗｗｗｗｗｗｗ(今この機能に気づいた人のお気持ち)

2020-04-18 05:29 UTC, loxygenK commented on lib/voice_manager.py
> +        self.is_join = True
```suggestion
        self.is_join = after.channel is not None
```
* ここで`is not`は`None`を否定しているわけではなくて`is not`で一つですぼくはPythonが嫌いです
  refer: https://qiita.com/tortuepin/items/44fdb63cc82dfd260575

2020-04-18 06:10 UTC, Colk-tech commented on lib/voice_manager.py
> +        self.is_join = None
これはクソコードです...
できる範囲で効率的なコーディングをしたつもりですがこれ以外思いつきません...
とりあえずこれは改善しないでおきます
リファクタ助かる....

2020-04-18 06:21 UTC, loxygenK approved these changes
今後の本リポジトリの発展を心より祈りつつ、本***お気持ち表明***の終了を宣言したいと思います。
誠にありがとうございました。

というわけで ***†Approve†***

2020-04-18 06:21 UTC, loxygenK commented on lib/voice_manager.py
> +        self.is_join = None
かなしいね…つよくいきよう

2020-04-18 06:21 UTC, loxygenK commented on lib/voice_manager.py
> +        ignore_members = [684295118643265548]
これは別にやってもやらなくてもなんにも変わらないのでどうでもいいんですが、`static_init`で初期化したほうがいいと思うんだが…

2020-04-18 09:14 UTC, isso0424 commented
読  み  ま  す

2020-04-18 09:31 UTC, Colk-tech commented
かわえそう

2020-04-18 09:34 UTC, isso0424 commented
レビューの量がどんどん増えてってウケる

2020-04-18 09:34 UTC, loxygenK commented
かなしいね…

2020-04-18 09:34 UTC, Colk-tech commented
わかる

2020-04-18 09:37 UTC, isso0424 commented
只今7

2020-04-18 09:37 UTC, isso0424 commented
只今7

2020-04-18 09:37 UTC, loxygenK commented
俺がsuggetstしたところもレビューされてそう

2020-04-18 09:38 UTC, isso0424 commented
待ってみてみる

2020-04-18 09:39 UTC, isso0424 commented
うーんsuggest自体にはしてないが同じ場所に別なレビューをしている

2020-04-18 09:39 UTC, Colk-tech commented
わかる

2020-04-18 09:40 UTC, loxygenK commented
安心した♡(人間の屑)

2020-04-18 09:41 UTC, isso0424 commented
私は設計とかなんもわからんので動きをできるだけそのままに読みやすく(当社比)している

2020-04-18 09:41 UTC, loxygenK commented
プロ

2020-04-18 09:42 UTC, isso0424 commented
しかしウンコーダー

2020-04-18 09:43 UTC, loxygenK commented
かなしいね
いいコードを書きたいね

2020-04-18 09:53 UTC, isso0424 commented
🤔🤔🤔🤔🤔
↑どこをどうしたらこうなるかわからん顔

2020-04-18 09:53 UTC, loxygenK commented
草
どこか気になる

2020-04-18 09:54 UTC, loxygenK commented
ちゃうどこをどうしたらいいのかわからんのだからどこかといわれてもわからんのか

2020-04-18 09:57 UTC, isso0424 requested changes
頭こんがらがって来たのでこのへんで ***REQUEST CHANGES***
なんで1classでこの2つの機能実装したんですか

2020-04-18 09:57 UTC, isso0424 commented on lib/voice_manager.py
> +        ignore_members = [684295118643265548]
これself.では

2020-04-18 09:57 UTC, isso0424 commented on lib/voice_manager.py
> +        instanceの状況に応じてembedを返す関数
返り値を書きましょう

2020-04-18 09:57 UTC, isso0424 commented on lib/voice_manager.py
> +        embed_out = discord.Embed(title=embed_title.format(self.member.display_name, str(self.before.channel)), description=embed_message, color=0x1e63e9)
ここ気になったんだが先にif文の中でformatしてはだめですか
1行が長え

2020-04-18 09:57 UTC, isso0424 commented on lib/voice_manager.py
> +    async def role_manager(self):
managerは直感的でない...
updateとかがいいと思う

2020-04-18 09:57 UTC, isso0424 commented on lib/voice_manager.py
> +class VoiceManager():
名前は`VoiceStateManager`とかいかが

2020-04-18 09:57 UTC, isso0424 commented on lib/voice_manager.py
> +            該当するメンバーののオブジェクト
こいつはidだけ引っ張ってくれば平和が訪れる

2020-04-18 09:57 UTC, isso0424 commented on lib/voice_manager.py
> +            変更後のVoiceStateオブジェクト
これ`channel`だけで動きますよね...?

2020-04-18 09:57 UTC, isso0424 commented on lib/voice_manager.py
> +        ignore_members = [684295118643265548]
というかそれどころかこれクラスにprivate定数として持たせるのが正しいでしょ

2020-04-18 09:57 UTC, isso0424 commented on lib/voice_manager.py
> +        cls.GUILD = guild
こいつクラス変数にする必要なくてウケる
これコード内で使ってるのmembersの取り出しだけですよ

2020-04-18 09:57 UTC, isso0424 commented on lib/voice_manager.py
> +    async def reset_roles(cls):
これ、roleの管理を別クラスに切り出すべきでは
このclass_method2つが邪魔すぎる

2020-04-18 09:57 UTC, isso0424 commented on lib/voice_manager.py
> +    async def reset_roles(cls):
ちなみにこれをやるとstatic_initが必要なくなります

2020-04-18 09:58 UTC, isso0424 commented
これ、なんで1classでやったんですか
役職の管理とembedの送信分けても問題ないでしょ()

2020-04-18 10:02 UTC, loxygenK commented
これ人のコメント編集できるんだけど
現実改変じゃん

2020-04-18 10:07 UTC, isso0424 commented
全員Ownerやし...

2020-04-18 10:08 UTC, loxygenK commented
Ownerこえー()

2020-04-18 10:08 UTC, isso0424 commented
まぢで

2020-04-18 10:23 UTC, loxygenK commented on lib/voice_manager.py
> +        ignore_members = [684295118643265548]
やっべ`self.`忘れてた
確かにprivate定数で良さそうですね‥()

2020-04-18 16:29 UTC, isso0424 requested changes
PR見てもらえなくてキレたので21個追加しておきました
***RE REQUEST CHANGES***

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +            url="https://cdn.discordapp.com/avatars/{}/{}.png".format(self.member.id, self.member.avatar))
urlくくり出せますよね

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +        self.after = None
こいつら使われていない

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +        self.member = None
selfで渡さないでください

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +        self.member = member
横着せずに引数で渡せカス

2020-04-18 16:29 UTC, isso0424 commented on main.py
> +        """
before,afterだと情報がすくないのでbefore_voice_stateとかにしてくれ( by ぬーちゃん)

2020-04-18 16:29 UTC, isso0424 commented on main.py
> +            編集後のメッセージオブジェクト
typehint書いた上でbefore_messageとかにしませんか

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +            if cls.LISTENER_ROLE in each_member.roles:
`roles_id = [role.id for role in each_member.roles]`
でidのリスト取ればLISTENER_ROLE取得必要無い

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +        listener_role_id = 700565764117233685
これクラス変数にしましょう

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +        cls.LISTENER_ROLE = guild.get_role(listener_role_id)
こいついらないです

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +    async def role_manager(self):
引数にmemberを入れよう

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +        await self.member.remove_roles(VoiceManager.LISTENER_ROLE)
self.である意味がない

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +            url="https://cdn.discordapp.com/avatars/{}/{}.png".format(self.member.id, self.member.avatar))
self.いらないです

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +        embed_out = discord.Embed(title=embed_title.format(self.member.display_name, str(self.before.channel)), description=embed_message, color=0x1e63e9)
self.いらないです

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +    def embed_generater(self):
memberを引数に取ろう

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +        self.after = after
found no usage.

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +        if after.channel == before.channel or member.id in VoiceManager.ignore_members:
左の式channelが先に出てればvoiceStateである意味が無い

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +    音声関連の処理をするクラス
voiceChannel関連の処理じゃないんですか()
音声はいじってないだろ

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +    async def reset_roles(cls):
てかここでguild渡せばstatic_initで渡す必要ないですね

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +                await each_member.remove_roles(cls.LISTENER_ROLE)
ここでID使ってget_roleすればstatic_initでやる必要ないです

2020-04-18 16:29 UTC, isso0424 commented on lib/voice_manager.py
> +        cls.KIKISEN_CHANNEL = kikisen_channel
必要だと思われるのはこいつだけなので先にNoneで定義しておいて
`VoiceManager.KIKISEN_CHANNEL = kikisen_channel`
すればいいのでは
ちなみにこれでstatic_init消えます

2020-04-18 16:29 UTC, isso0424 commented on main.py
> +        self.voice_diff = None
found no usage.

2020-04-19 12:37 UTC, Colk-tech commented
ちなみにクラス切り出して書き直すとPreviewがほぼ直せなくなるというバグがあるんですよ

2020-04-24 14:45 UTC, Colk-tech commented
`Uncoder`ブランチにて書き直しの刑

2020-04-24 14:51 UTC, Colk-tech commented
このPRはcloseされます
#117 が新しいやつだよ

2020-04-24 14:51 UTC, closed without merging