[WIP] とりあえず完成
brokenManager/OreOreBot pull request #120
Opened 2020-04-30 07:29 UTC by Colk-tech

これはお願いなんですけど、Reviewするときは小出しにしてほしいなぁ...()
とりあえず動くようにはなってるのでpylintくんを黙らせる作業をします

2020-04-30 07:57 UTC, Colk-tech commented
これはお願いなんですけど、Reviewするときは小出しにしてほしいなぁ...()
pylintくんを黙らせたのでよろしくおねがいします（小声）

2020-04-30 08:04 UTC, Colk-tech commented
とりあえずローカル止めたいのでデプロイしました...
亭ゆるして...

2020-04-30 08:12 UTC, Colk-tech commented
いやWIPとれよ

2020-04-30 09:37 UTC, loxygenK commented
お風呂入ったらレビューするつもり♥

2020-04-30 23:18 UTC, loxygenK requested changes
バグを見つけたので***Request Change***をどうぞ
それ以外には特に気になる点はありませんでした

2020-04-30 23:18 UTC, loxygenK commented on lib/message_debug.py
> +    if debug_text in "`":
```suggestion
    if "`" in debug_text:
```
^^

2020-05-01 01:00 UTC, Colk-tech commented
これはガバ

2020-05-01 05:51 UTC, loxygenK submitted a review, later dismissed
okだと思います :thumbsup:

2020-05-01 09:40 UTC, Colk-tech commented
やったぜ
珍しく修正が少なくて嬉しいね

2020-05-01 09:40 UTC, Colk-tech commented
まぁラスボスがいるんですけど

2020-05-01 14:46 UTC, isso0424 commented
見　に　来　た　よ　♡

2020-05-01 14:47 UTC, Colk-tech commented
ラスボスの品評会楽しいね

2020-05-01 14:59 UTC, isso0424 requested changes
今見て思いついた範囲だとこんな感じ

2020-05-01 14:59 UTC, isso0424 commented on lib/message_debug.py
> +    """
これはdiscordが悪いのかもしれないけどmessageの中身とchannelを引数としてとりませんか

そうするとこの関数が1行になります

2020-05-01 14:59 UTC, isso0424 commented on lib/message_debug.py
> +
***†ガード忘れ†***

2020-05-01 14:59 UTC, isso0424 commented on lib/message_debug.py
> +
エラーでメッセージのバグを取り除くとは思わなかった()

これ
IndexError => len(commands)
ValueError => commands[1].isdecimal()
で代用しようぜ

あと追加で言うとこの時点でIDの桁数を取ってreturnしてしまっても良いかもしれない

2020-05-01 14:59 UTC, isso0424 commented on lib/message_debug.py
> +    await send_result(debug_text=debug_text, respond_channel=respond_channel)
これキーワード引数である意味ないと思うんですが私だけでしょうか

2020-05-01 14:59 UTC, isso0424 commented on main.py
> +            await debug_on_edit(message=before)
なんで引数1個なのにキーワード引数...?

2020-05-01 14:59 UTC, isso0424 commented on message_command.py
> +        if commands[0].lower() in ["debug", "d"]:
これ前から思ってたんですが
command = commands[0].lower()
って先にやったほうがスマート

2020-05-01 14:59 UTC, isso0424 commented on lib/message_debug.py
> +        await respond_channel.send("そんなidのメッセージは存在しないよ...?\nそのメッセージのあるチャンネルで試してみてね")
エラーメッセージにこのチャンネルには無いっていう明記が必要だと思う
「このチャンネルにはそのidのメッセージは存在しないよ...?」って感じで

2020-05-01 14:59 UTC, isso0424 commented on lib/message_debug.py
> +    commands: list[str]
これ[1]しか使ってないからlistである意味ない

2020-05-01 15:00 UTC, Colk-tech commented on main.py
> +            await debug_on_edit(message=before)
草

2020-05-01 15:00 UTC, Colk-tech commented on main.py
> +            await debug_on_edit(message=before)
カスじゃん

2020-05-01 15:04 UTC, Colk-tech commented on lib/message_debug.py
> +    commands: list[str]
あーたしかに

2020-05-01 15:08 UTC, Colk-tech commented on message_command.py
> +        if commands[0].lower() in ["debug", "d"]:
たしかに

2020-05-01 15:15 UTC, Colk-tech commented on lib/message_debug.py
> +
楽なので...()

2020-05-01 15:16 UTC, isso0424 commented on lib/message_debug.py
> +
キレそう

2020-05-01 15:22 UTC, Colk-tech commented on lib/message_debug.py
> +    commands: list[str]
1が無い例外の時を考えて残すことにしました(`len(commands)`の修正と競合する)
判定処理をmessage commandsに持っていけばいいだけの話ですがなんか嫌なのでこのままです

2020-05-01 15:23 UTC, Colk-tech commented on lib/message_debug.py
> +
IDの桁数は試したら不定だったので実装できませんでした...
まぁどうせNotFoundで拾ってくれる

2020-05-01 15:24 UTC, isso0424 commented on lib/message_debug.py
> +    commands: list[str]
なんでや分岐に`and len(commands) >= 2`ってするだけやろ...

2020-05-01 15:36 UTC, Colk-tech commented on lib/message_debug.py
> +    commands: list[str]
（いまさら発見してしまったときの音）

2020-05-01 15:37 UTC, isso0424 requested changes

2020-05-01 15:37 UTC, isso0424 commented on message_command.py
> +            return
```suggestion
        if command_name in ["debug", "d"] and len(commands)  >= 2:
            await debug_on_message(commands[1], respond_channel=self.channel)
            return
```
これじゃ駄目なんですか...
list渡す意味が見えません...

2020-05-01 15:37 UTC, isso0424 commented on lib/message_debug.py
> +        await respond_channel.send("このチャンネルにはそのidのメッセージは存在しないよ...?...?\nそのメッセージのあるチャンネルで試してみてね")
`存在しないよ...?...?` is 何(これは煽りです)

2020-05-01 15:41 UTC, isso0424 commented on lib/message_debug.py
> +
それならいいや(諦め)

2020-05-01 15:42 UTC, Colk-tech commented on message_command.py
> +            return
最新のコミットでやった（時間差）

2020-05-01 15:42 UTC, Colk-tech commented on lib/message_debug.py
> +        await respond_channel.send("このチャンネルにはそのidのメッセージは存在しないよ...?...?\nそのメッセージのあるチャンネルで試してみてね")
草
煽り草

2020-05-01 15:42 UTC, Colk-tech commented on lib/message_debug.py
> +        await respond_channel.send("このチャンネルにはそのidのメッセージは存在しないよ...?...?\nそのメッセージのあるチャンネルで試してみてね")
しかもrequest changesで草

2020-05-01 15:47 UTC, isso0424 requested changes
pythonにも型は(一応)あるんやで...

2020-05-01 15:47 UTC, isso0424 commented on lib/message_debug.py
> +        return
どうして...

2020-05-01 15:47 UTC, isso0424 commented on lib/message_debug.py
> +    target_message_id = int(target_message_id)
ちょっと待てこれは変数名変えようね
1mmくらいは型を意識しよう

2020-05-01 15:48 UTC, Colk-tech commented on lib/message_debug.py
> +        return
草

2020-05-01 15:48 UTC, isso0424 commented on lib/message_debug.py
> +        return
ごめんこれの1行上だわ

2020-05-01 15:48 UTC, Colk-tech commented on lib/message_debug.py
> +    target_message_id = int(target_message_id)
p   y   t   h   o   n   の   後   型   付   け

2020-05-01 15:53 UTC, Colk-tech commented on lib/message_debug.py
> +        return
わかったのでセーフ

2020-05-01 15:54 UTC, isso0424 requested changes

2020-05-01 15:54 UTC, isso0424 commented on message_command.py
> +            await debug_on_message(target_message_id=commands[1], respond_channel=self.channel)
これキーワード引数である意味無くね

急にキーワード引数で取られると変な感じがする(ここまでやってなかったから)

2020-05-01 15:55 UTC, isso0424 commented
何度もすまんが最後のは本当に気になってしまったので許してくれ...

2020-05-01 15:58 UTC, Colk-tech commented on message_command.py
> +            await debug_on_message(target_message_id=commands[1], respond_channel=self.channel)
世話かけてごめんなのだ...
by ウンコーダーより

2020-05-01 15:58 UTC, isso0424 commented
`a = int(a)`やめませんか...

2020-05-01 15:59 UTC, Colk-tech commented
あれっ解消されてなかった？

2020-05-01 16:05 UTC, Colk-tech commented
1時なので寝ます...

@isso0424 これで大丈夫だったらApprove&Mergeをしてほしいなっ！
世話かけてごめんなのだ...
by ウンコーダーより

2020-05-01 16:06 UTC, isso0424 commented on lib/message_debug.py
> +    parsed_message_id = int(target_message_id)
`target_message_id = int(received_message)`
とかいう命名はどうですか...
discord.pyではidはintで扱われるのでstrとか入れるならidって言う文字列を変数名に入れるの良くないと思う

最初っからこれぐらい言えばよかったなすまん

2020-05-01 16:09 UTC, Colk-tech commented on lib/message_debug.py
> +    parsed_message_id = int(target_message_id)
いきててごめんなさい...
(よわよわ並感)

2020-05-01 18:46 UTC, isso0424 approved these changes

2020-05-01 18:47 UTC, merged

2020-05-02 02:23 UTC, Colk-tech commented
MERGEお゛い゛じい゛♡♡♡♡♡♡♡