[WIP] 服役はしてないと良いね
brokenManager/OreOreBot pull request #128
Opened 2020-05-11 08:14 UTC by Colk-tech

2020-05-11 09:37 UTC, loxygenK reviewed
バグとかはなさそうだけどいくつか気になった点があるので**Comment**

2020-05-11 09:37 UTC, loxygenK commented on lib/hukueki.py
> +"""
```suggestion
"hukueki": "```\n" +
           "ねぇ、将来何してるだろうね\n" +
           "{}はしてないと良いね\n" +
           "困らないでよ\n" +
           "```",
"lolicon": "```だから僕は{}を辞めた - {} (Music Video)```"
```

2020-05-11 09:37 UTC, loxygenK commented on lib/hukueki.py
> +def text_parser(raw_text: str):
```suggestion
def escape_md_char(raw_text: str):
```

2020-05-11 09:37 UTC, loxygenK commented on lib/hukueki.py
> +    parsed_content = text_parser(raw_content)
```suggestion
    parsed_content = escape_md_char(content)
```

2020-05-11 09:37 UTC, loxygenK commented on lib/hukueki.py
> +def text_parser(raw_text: str):
text_parserちゃん、他のところでも頻繁に使われそうな関数なので別のファイル(`utils.py`)とかに投げたほうがいいかもしれない

2020-05-11 09:37 UTC, loxygenK commented on lib/hukueki.py
> +async def hukueki(raw_content: str, respond_ch: discord.TextChannel):
```suggestion
async def hukueki(content: str, respond_ch: discord.TextChannel):
```

2020-05-11 09:37 UTC, loxygenK commented on lib/hukueki.py
> +async def lolicon(raw_content: str, member_name: str, respond_ch: discord.TextChannel):
```suggestion
async def lolicon(content: str, member_name: str, respond_ch: discord.TextChannel):
```

2020-05-11 09:37 UTC, loxygenK commented on lib/hukueki.py
> +    parsed_content = text_parser(raw_content)
```suggestion
    parsed_content = text_parser(content)
```

2020-05-11 09:39 UTC, Colk-tech commented on lib/hukueki.py
> +def text_parser(raw_text: str):
別issue行きとしますん

2020-05-11 09:42 UTC, loxygenK requested changes
ガバを発見しました

2020-05-11 09:42 UTC, loxygenK commented on lib/hukueki.py
> +    parsed_content = text_parser(content)
```suggestion
    parsed_content = escape_md_char(content)
```

2020-05-11 09:43 UTC, Colk-tech commented on lib/hukueki.py
> +    parsed_content = text_parser(content)
先に下のcommitで解消しちゃってました...
いきててごめんなさい...

2020-05-11 09:44 UTC, loxygenK approved these changes
***†Approved†***
あとはいっそうくんのレビューをまとうね

2020-05-12 14:23 UTC, isso0424 approved these changes

2020-05-12 14:26 UTC, merged