New haracho message monitor
brokenManager/OreOreBot pull request #137
Opened 2020-06-08 11:58 UTC by loxygenK

いろいろガバってコミット履歴ぐっちゃぐちゃなのでRequest Change投げてくれたらRebaseして投げ直します
し　　ん　　ど　　い

2020-06-08 12:00 UTC, loxygenK commented
どうして同じコミットが２つあるんですか？

2020-06-08 14:47 UTC, isso0424 requested changes
***よくない***

2020-06-08 14:47 UTC, isso0424 commented on src/on_message/modify/delete.py
> +async def delete_notify(message: discord.Message):
`delete_notify`は`notify_message_delete`でよくね

2020-06-08 14:47 UTC, isso0424 commented on src/on_message/modify/edit.py
> +async def edit_notify(
`delete`と同様に`notify_message_edit`で良いと思う

2020-06-08 14:47 UTC, isso0424 commented on src/on_message/modify/edit.py
> +    modified_diff = [x for x in raw_diff if x[:1] in "+-"]
`"+-"`は`["+", "-"]`で良いと思う

2020-06-08 14:47 UTC, isso0424 commented on src/on_message/modify/edit.py
> +    modified_diff = [x for x in raw_diff if x[:1] in "+-"]
てか`+`, `-`をkeyとするdictにすればstepが要らなくなります

2020-06-08 14:47 UTC, isso0424 commented on src/on_message/modify/delete.py
> +    """.replace(" ", "")
このインデントいる...?

2020-06-09 01:21 UTC, isso0424 requested changes

2020-06-09 01:21 UTC, isso0424 commented on src/client.py
> -
け　す　な

2020-06-09 01:21 UTC, isso0424 commented on src/message_delete/delete.py
> +    )
世界なぜ改行しない

2020-06-09 01:21 UTC, isso0424 commented on src/message_edit/edit.py
> +    return generated_diff_text.strip()
世界なぜk(ry

2020-06-09 01:21 UTC, isso0424 commented on src/message_edit/edit.py
> +    for i in range(len(modified_diff) // 2):
これは`len(diff_dict["+"])`すればマジックナンバーが要らなくなる

2020-06-09 01:21 UTC, isso0424 commented on src/message_edit/edit.py
> +    modified_diff = [x for x in raw_diff if x[:1] in "+-"]
この変数いらなくね

2020-06-09 01:21 UTC, isso0424 commented on src/message_edit/edit.py
> +            HORIZONTAL_LINE if (i * 2) != len(modified_diff) - 2 else ""
ここ`modified_diff`を`diff_dict["+"]`にすれば`i * 2`である意味が無いと思われ

2020-06-09 15:16 UTC, isso0424 approved these changes
(多分)問題ない

2020-06-09 22:40 UTC, loxygenK commented
やったぜ。
これ僕がマージ処理してええんか？
（していいならsquashするつもり）

2020-06-10 05:37 UTC, merged