いっぱい出入りしたときに声を抑えるようにした
brokenManager/OreOreBot pull request #143
Opened 2020-08-10 15:34 UTC by loxygenK

出入りが激しいといっぱい流れてしまって見づらくなってやだ

今のところは1秒以下の間隔で出入りすると声を抑えるようにしてあります :bow:

2020-08-11 14:14 UTC, isso0424 commented on lib/voice_diff.py
> +        if (datetime.datetime.now() - prev_time) <= VoiceDiffHandler.TIME_INTERVAL_LIMIT:
一々計算するの...無駄じゃない...?

2020-08-11 14:16 UTC, isso0424 requested changes

2020-08-11 14:16 UTC, isso0424 commented on lib/voice_diff.py
> +        self.hisotry[member.id] = datetime.datetime.now()
dateTime使いまわそうぜ

2020-08-11 14:37 UTC, loxygenK commented on lib/voice_diff.py
> +        self.hisotry[member.id] = datetime.datetime.now()
774d7d0

2020-08-11 14:37 UTC, loxygenK commented on lib/voice_diff.py
> +        if (datetime.datetime.now() - prev_time) <= VoiceDiffHandler.TIME_INTERVAL_LIMIT:
774d7d0

2020-08-16 02:51 UTC, soshiharami requested changes

2020-08-16 02:51 UTC, soshiharami commented on lib/voice_diff.py
>  無駄にクラス化してもしゃーないかーってことで関数になりました
クラス化してるやんの顔をしている

2020-08-16 03:05 UTC, loxygenK commented on lib/voice_diff.py
>  無駄にクラス化してもしゃーないかーってことで関数になりました
気づかなかった、変えます

2020-08-16 03:07 UTC, soshiharami commented on lib/voice_diff.py
>  無駄にクラス化してもしゃーないかーってことで関数になりました
:pro:

2020-08-16 09:59 UTC, isso0424 approved these changes

2020-08-16 10:00 UTC, Colk-tech approved these changes
***卍 無責任Approve 卍***

2020-08-16 10:00 UTC, soshiharami approved these changes

2020-08-16 10:00 UTC, merged